### PR TITLE
ENH: add code, pragmas, and NC settings for imagers

### PR DESCRIPTION
**Pull request by ZLLentz**
I'll rebuild the IOC tomorrow and update this PR

### CODE REVIEW

**Comment by klauer** [comment]
Clean diff + line numbers were removed. Will look again when the IOC gets pushed today. 👍

**Comment by ZLLentz** [comment]
Pushed the IOC a week late. I'm pretty sure things aren't quite right yet though...

**Comment by ZLLentz** [comment]
Travis is doing something dumb because I accidentally pushed this branch to the upstream

**Comment by ZLLentz** [comment]
Next is to resolve the merge conflicts, hopefully it's not too bad. Maybe next week though.

**Comment by ZLLentz** [comment]
I resolved the issues and the build looks ok... The PLC project is in a weird spot because:
1. We have an error in my initial allocation of SL1K0 terminals
2. We have pragmas pointing to different names for the SL1K0 terminals
3. The parameters for IM1K0 are wrong (learned the correct setup during my IM1L0 adventure on Friday)
4. RTDSK0 is delayed a bit
5. As is PF1K0

I am going to merge as-is and work on a follow-up to make the project run with SL1K0 connected.

**Pull request merged**
