### PR TITLE
MNT: update library versions

### LINKED ISSUE #57: Update motion, cclib versions during PAMM
To get lens relative encoder homing, position saving working

### PR DESCRIPTION
**Pull request by ZLLentz**
motion -> to pick up relative encoder handling
cclib -> to pick up relative encoder config for lens motors
pmps -> to pick up bugfixes from @slacAWallace 

closes #57 

I do not think there is other work happening here during pamm- maybe @klauer is doing #56?
If nothing else is going on, then I will follow-up with a plc/ioc rebuild, a merge, and a deploy

### CODE REVIEW

**Comment by klauer** [comment]
As far as #56, I have not yet bumped the versions.

**Comment by ZLLentz** [comment]
Are you intending to do a fix to #56 during the PAMM?

I'm being extra careful because Beckhoff is dumb and I don't want anyone to have to redo anything or read a large merge conflict stack in an xml file just because we worked on two things at once. If you're going to work on that, then I will wait to merge this until after, otherwise I will do this right away.

**Comment by klauer** [comment]
If you would advise getting the changes in during this PAMM, I will do so. I had reprioritized the attenuator work to at least the upcoming PAMM in my mind after it failed to make the task list.

**Comment by ZLLentz** [comment]
I don't really care whether or not you look at the attenuator during the PAMM- I just wanted to know. I'll proceed here then under the assumption you're looking at other things.

**Comment by klauer** [comment]
The intent was not clear to me, which is why I was trying to see if there was a good reason to do the update now.

**Comment by ZLLentz** [comment]
Ok, sorry for being unclear. I'll proceed with the remaining steps here (rebuilding the tmc/ioc) that usually cause merge conflicts.

**Review by klauer — APPROVED** [review]
I see the relative encoder stuff in there, the (unfortunate) addition of position states, indicating it has the latest changes.

Database looks fine. Was surprised not to see any autosave pass1 entries, but I suppose vacuum is the primary end-user for those.

**Comment by ZLLentz** [comment]
True on the pass1- there's a reason why I haven't noticed anything wrong, after all.

**Pull request merged**
