### PR TITLE
ENH: AT1K4 commissioning filter positions (and nTran fix for IM2K0)

### LINKED ISSUE #64: AT1K4 axes are reversed 3 times, making MMS:01 downstream
* The attenuator was installed in reverse (the SME later admitted this was a known possibility but did not mention it)
* The axes were wired up in reverse (downstream/upstream were swapped)
* The PLC project was configured to reverse the miswiring

The above 3 things together make it such that the fixed PLC/miswired box/flipped install is *now* inconsistent in what we expect the upstream-most axis to be.

### PR DESCRIPTION
**Pull request by klauer**
Reference: https://confluence.slac.stanford.edu/display/L2SI/AT1K4-SOLID+SXR+Solid+Attenuator

Closes #64

### CODE REVIEW

**Comment by ZLLentz** [comment]
Looks good to me! Does this close #64 with the comment changes with the upstream/downstream specification?

**Review by ZLLentz — APPROVED** [review]

**Comment by klauer** [comment]
I think we can close that issue now. 👍 

This is now deployed. Did not include the tmc yet - want me to add it to the PR?

**Comment by ZLLentz** [comment]
Should include the tmc if it changes the IOC, otherwise I don't really have an opinion

**Comment by klauer** [comment]
OK, I think this is good-to-go then 👍 👏

**Pull request merged**
